-- Drop unused tables
DROP TABLE IF EXISTS leases CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS kv_store_3f6e5f02 CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS config CASCADE;