// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrknfweilbuwrhzzwnrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya25md2VpbGJ1d3Joenp3bnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MjkwODksImV4cCI6MjA4MzMwNTA4OX0.djk3RquoU5Bu-cTF6BTgu2RKYQ7vh-E5HgkLBuR9sNQ";

// Validação de chaves
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Chaves do Supabase não configuradas');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    storageKey: 'rental-auth-token',
  },
  global: {
    headers: {
      'x-client-info': 'rental-management',
    },
    fetch: (url, options: RequestInit = {}) => {
      return fetch(url, {
        ...options,
        signal: options.signal,
      });
    },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Monitorar eventos de autenticação
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token atualizado');
  } else if (event === 'SIGNED_OUT') {
    console.log('Usuário desconectado');
  } else if (event === 'SIGNED_IN') {
    console.log('Usuário autenticado');
  }
});

export const setSupabaseSession = async (accessToken: string, refreshToken: string) => {
  try {
    const { data, error } = await supabase.auth.setSession({
      access_token: accessToken,
      refresh_token: refreshToken,
    });
    
    if (error) {
      console.error('Erro ao configurar sessão:', error);
      return false;
    }
    
    return true;
  } catch (err) {
    console.error('Erro ao configurar sessão:', err);
    return false;
  }
};

export const getSupabaseSession = async () => {
  try {
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Erro ao obter sessão:', error);
      return null;
    }
    
    return session;
  } catch (err) {
    console.error('Erro ao obter sessão:', err);
    return null;
  }
};

// Health check aprimorado para detectar projeto pausado
export const checkSupabaseHealth = async (): Promise<{
  healthy: boolean;
  status: 'healthy' | 'paused' | 'unhealthy' | 'network_error';
  message: string;
}> => {
  try {
    console.log('🏥 Verificando saúde do Supabase...');
    
    // Criar AbortController com timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
      controller.abort(new Error('Health check timeout após 30 segundos'));
    }, 30000);
    
    try {
      const { data, error } = await supabase
        .from('system_users')
        .select('id')
        .limit(1)
        .abortSignal(controller.signal);
      
      clearTimeout(timeoutId);
      
      if (error) {
        console.error('❌ Erro no health check:', error);
        
        // Detectar projeto pausado
        if (error.message?.includes('Failed to fetch') || error.message?.includes('NetworkError')) {
          return {
            healthy: false,
            status: 'paused',
            message: '🛑 Projeto Supabase pausado ou offline. Acesse o dashboard do Supabase para reativá-lo.'
          };
        }
        
        return {
          healthy: false,
          status: 'unhealthy',
          message: `⚠️ Serviço do Supabase com problemas: ${error.message}`
        };
      }
      
      console.log('✅ Supabase funcionando normalmente');
      return {
        healthy: true,
        status: 'healthy',
        message: '✅ Conexão estabelecida com sucesso'
      };
    } catch (queryError: any) {
      clearTimeout(timeoutId);
      
      // Tratar erro de abort
      if (queryError.name === 'AbortError') {
        console.warn('⏱️ Health check abortado por timeout');
        return {
          healthy: false,
          status: 'network_error',
          message: '⏱️ Timeout ao conectar ao Supabase. Verifique sua conexão.'
        };
      }
      
      throw queryError;
    }
    
  } catch (err: any) {
    console.error('❌ Erro crítico no health check:', err);
    
    // Detectar erro de rede/projeto pausado
    if (err.name === 'AbortError' || err.message?.includes('fetch') || err.message?.includes('timeout')) {
      return {
        healthy: false,
        status: 'paused',
        message: '🛑 Não foi possível conectar ao Supabase. O projeto pode estar pausado ou offline.'
      };
    }
    
    return {
      healthy: false,
      status: 'network_error',
      message: '❌ Erro de rede ou conexão. Verifique sua internet e o status do Supabase.'
    };
  }
};